# Generated by Django 4.0.6 on 2022-08-10 21:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versus_type', models.CharField(choices=[(0, 'Versus'), (1, 'Bot')], default='Versus', max_length=10)),
                ('game_uuid', models.UUIDField(default=uuid.UUID('07953daf-c62a-4b81-8d42-7a613b2a3e94'), editable=False)),
                ('status', models.CharField(choices=[(0, 'In_Progress'), (1, 'Finished')], default='In_Progress', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='sessions.session')),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_player', to='sessions.session')),
                ('players', models.ManyToManyField(to='sessions.session')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('6a1a6f51-e945-4806-bbf2-e94f1cbe399d'), editable=False)),
                ('positions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5, null=True), blank=True, null=True, size=None)),
                ('player_mark', models.CharField(choices=[('x', 'X'), ('O', 'O')], default='X', max_length=3)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
            ],
        ),
    ]
