# Generated by Django 4.0.6 on 2022-08-03 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_uuid',
            field=models.UUIDField(default=uuid.UUID('7c4e02ae-446d-4953-8629-fbf9f301c9f4'), editable=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('589b7170-ab07-4511-a953-0ecea938aca0'), editable=False),
        ),
    ]
