# Generated by Django 4.0.6 on 2022-08-12 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_move_count_alter_game_game_uuid_alter_move_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_uuid',
            field=models.UUIDField(default=uuid.UUID('0c6c108b-4b7a-45ff-b850-8221ee948ead'), editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='move_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='move',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4a0a27c7-9989-4f68-a845-e1b8f163e35a'), editable=False),
        ),
    ]
