# Generated by Django 4.0.6 on 2022-08-03 19:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_game_uuid_alter_move_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_uuid',
            field=models.UUIDField(default=uuid.UUID('58f35a15-1969-4086-9878-a9fde352e8c1'), editable=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='moves', to='game.game'),
        ),
        migrations.AlterField(
            model_name='move',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ef7fa4df-f0ad-4d9e-af49-e729e1324e27'), editable=False),
        ),
    ]
