# Generated by Django 4.0.6 on 2022-08-17 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_game_uuid_alter_game_move_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_uuid',
            field=models.UUIDField(default=uuid.UUID('e832d418-8008-42ee-9d0e-6dfa1750bfae'), editable=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1dc2488e-dce9-45aa-9de6-7a78d4f4aeca'), editable=False),
        ),
    ]
