# Generated by Django 4.0.6 on 2022-08-06 15:00

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_game_uuid_alter_move_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_uuid',
            field=models.UUIDField(default=uuid.UUID('18ad070f-c151-41c8-a28c-38839d6874ed'), editable=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='move',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5b419fe3-f638-42c2-adb0-7a43ac22527b'), editable=False),
        ),
    ]
