# Generated by Django 4.0.6 on 2022-08-06 15:01

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_game_game_uuid_alter_move_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_uuid',
            field=models.UUIDField(default=uuid.UUID('a3939eb1-8978-476b-ac53-cae666e389f5'), editable=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='move',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bba498c6-ab49-4289-8acd-0d8a4a6ff555'), editable=False),
        ),
    ]
