# Generated by Django 4.0.6 on 2022-08-07 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_created_by_alter_game_game_uuid_alter_move_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='versus_type',
            field=models.CharField(choices=[(0, 'Versus'), (1, 'Bot')], default='Versus', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_uuid',
            field=models.UUIDField(default=uuid.UUID('f91ce446-b633-4d63-bd44-a34b8a7a1efa'), editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[(0, 'In_Progress'), (1, 'Finished')], default='In_Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='move',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f3fd4746-e633-4c34-bae7-3fd2dd86df9b'), editable=False),
        ),
    ]
